### ISSUE TITLE
Logo.ico missing

### ISSUE THREAD

**Issue by gnollhide** [Mastercorp/StarCategorizer#1]
In Ubuntu 17.04, running StarCategorizer.py in Python 2.7.14 pulls up error 

`Traceback (most recent call last):
  File "./StarCategorizer.py", line 153, in <module>
    viewer = View.View()
  File "/home/jazz/.local/share/Steam/userdata/(my steam ID)/7/remote/View.py", line 15, in __init__
    self.master.iconbitmap(self.resource_path('logo.ico'))
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1701, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "/home/jazz/.local/share/Steam/userdata/(my steam ID)/7/remote/logo.ico" not defined`

If the lines referencing logo.ico in view.py are commented out, it runs just fine.

**Comment by gnollhide** [comment]
Just an update, the same logo.ico is missing for the categories popup, which causes it to render a blank grey box. Commenting out `window.iconbitmap(self.resource_path('logo.ico'))` in view.py causes the box to pull up and work as normal.

**Comment by tuong59** [comment]
from tkinter import *
from PIL import Image, ImageTk 
from googletrans import Translator

root=Tk()
root.title('google Galaxy')
root.geometry("500x360")
root.iconbitmap('logo.ico')

root.mainloop()  
return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "logo.ico" not defined
